### ISSUE TITLE
Remover o espaço em branco entre seções do conteúdo

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#1]
Gosto bastante dessa transição por cores no background, usando toda a extensão horizontal da página. 

![screen shot 2017-07-24 at 11 14 11](https://user-images.githubusercontent.com/3904166/28527576-5087928a-7061-11e7-9fbf-145aecc13b40.png)

**Comment by greevin** [comment]
As margens do lado esquerdo e direito foram removidas. A primeira e a terceira seção agora estão com o background branco e a segunda e quarta seção estão com background transparente usando a cor do fundo (que é cinza).
