### ISSUE TITLE
Projeto, caixa "Mais detalhes" reestilizar

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#10]
Gostei do azul e branco aqui! Falta que:

- Ocupe toda a extensão horizontal (acho que isso é um cometário geral para todas as páginas e posts - essa margem a direita em cinza fica feia).
- Podemos remover "mais detalhes" do título e ir direto pras informações.

![screen shot 2017-07-26 at 15 23 18](https://user-images.githubusercontent.com/3904166/28637068-a3b9df1a-7216-11e7-8ed1-755bc7d9c864.png)

**Comment by greevin** [comment]
Foi adicionado uma tabela para distribuir melhor as informações na tela com a borda branca embaixo.

![detalhes](https://user-images.githubusercontent.com/7833013/28740533-28c573ec-73dc-11e7-8d4d-c8424454b24b.png)
