### ISSUE TITLE
Clica em "pessoas" no menu vai para outro estilo

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#11]
![screen shot 2017-07-26 at 15 26 13](https://user-images.githubusercontent.com/3904166/28637122-cad41f8e-7216-11e7-9abe-a7df19098981.png)

**Comment by greevin** [comment]
O estilo da página 'Pessoas' agora está com o mesmo estilo que está sendo apresentado na tela inicial.

![catedra dev-pessoas- 1](https://user-images.githubusercontent.com/7833013/28740503-db942a3c-73db-11e7-8769-4322682114c9.png)
