### ISSUE TITLE
Mudar cor do fundo menu e texto

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#13]
Achei rápido onde mudar o fundo, mas não há um para mudar texto. Prefiro o fundo com o azul que falamos (#123652) e texto branco. Ai, quando essa cor aparecer no lado direito, cria uma fluidez bacana. Mas veja que há um erro aqui na conexão entre as caixas:

![screen shot 2017-07-26 at 15 34 12](https://user-images.githubusercontent.com/3904166/28637482-123fb198-7218-11e7-923a-42b19636860d.png)

Gostei da seleção dos azuis. Acho que ambos azuis mais um cinza, preto e branco ficam ótimos como paleta de cores.

**Comment by tamielbr** [comment]
Acabei de pensar que isso pode ser ruim por conta da logo que aparecerá no topo do menu. Me diga o que pensa. Sendo assim, podemos seguir com branco mesmo.

**Comment by greevin** [comment]
Se for manter somente o nome, como está atualmente, está bem bacana com essa cor. Caso precise usar o logo, então será necessário voltar pro branco com as letras azuis.

![catedra dev-wp-admin-customize php-url http 3a 2f 2fcatedra dev 2f changeset_uuid f1790859-6988-4015-8794-030b69036b0d](https://user-images.githubusercontent.com/7833013/28676348-d351c954-72c0-11e7-8415-36a68845a14e.png)
