### ISSUE TITLE
Projetos e pessoas não aparecem em "Mais informações"

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#14]
Adicionei, selecionando os projetos de pesquisa no formulário mas eles não aparecem.
![screen shot 2017-07-26 at 15 30 14](https://user-images.githubusercontent.com/3904166/28637518-311d014c-7218-11e7-9355-20057d57e6e0.png)
![screen shot 2017-07-26 at 15 37 15](https://user-images.githubusercontent.com/3904166/28637569-633a00f8-7218-11e7-811d-769f61795641.png)
A ideia é que eles apareçam, com links para os projetos:
Pensei que aqui poderíamos fazer algo similar com a flechinha:

``Projetos``
``-> O último adeus de Sherlock Holmes``
``->O vale do terror``
``...``

**Comment by greevin** [comment]
Na página estava com o valor errado para recuperar as informações do projeto, a questão já foi corrigida. Além disso, foi adicionado os links para o projeto em questão com a seta.

![detalhes](https://user-images.githubusercontent.com/7833013/28740487-9e4277ce-73db-11e7-9db7-adb237af0681.png)
