### ISSUE TITLE
Reduzir tamanho de fontes

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#15]
Acho que está tudo um pouco grande. Podemos pensar em reduzir um pouco o padrão? Tenho medo de ficar com frases cortadas no meio, no menu, por exemplo que de todo modo pode expandir e ocupar um pouco mais da margem direita (mais texto).

![screen shot 2017-07-26 at 20 59 36](https://user-images.githubusercontent.com/3904166/28648613-5f09c50e-7245-11e7-946d-a24e76483782.png)

**Comment by greevin** [comment]
Diminui a fonte para 14px e coloquei o menu um pouco mais pra esquerda, com isso o texto mais longo ficou na mesma linha. Simulado como se fosse um laptop de 1440 x 372 no Chrome.

![catedra dev- 2](https://user-images.githubusercontent.com/7833013/28741494-569e30d6-73ed-11e7-967f-2523f4a7e892.png)
