### ISSUE TITLE
Verificar adequação de CSS para telas maiores

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#16]
Firefox MAC - se dou ``CMD -`` ele começa a desestruturar.

![screen shot 2017-07-26 at 21 00 28](https://user-images.githubusercontent.com/3904166/28648626-7d252916-7245-11e7-8459-67f66eaff34c.png)

**Comment by greevin** [comment]
Essa parte foi corrigida acertando as proporções da sidebar e do content. O sidebar ficou com 25% e o content com 75%, agora os lados ficam corretos sem ocorrer o problema acima.
