### ISSUE TITLE
Refinar a caixa de comentário

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#17]
Seguindo #7 - acho que aqui podemos simplificar e tirar ``site``.

![screen shot 2017-07-26 at 20 56 21](https://user-images.githubusercontent.com/3904166/28648586-3b501122-7245-11e7-8c6a-e35d92adeea7.png)

**Comment by greevin** [comment]
Retirado o campo 'Site' no campo de formulário. Subi os campos 'Nome' e 'E-mail' para antes da caixa de 'Comentário' e coloquei os dois campos na mesma linha.

![comentario](https://user-images.githubusercontent.com/7833013/28700734-fa19758e-7327-11e7-9ebf-5c93146cc08a.png)
