### ISSUE TITLE
Alinhamento das caixas está fora 

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#18]
Na página interna de projetos e pessoas temos algo assim, invadindo o cabeçalho.
![screen shot 2017-07-29 at 15 14 49](https://user-images.githubusercontent.com/3904166/28747265-18563416-7471-11e7-9603-e20a8808d406.png)

Um ajuste rápido dá isso:
![screen shot 2017-07-29 at 15 16 58](https://user-images.githubusercontent.com/3904166/28747269-2645e634-7471-11e7-927d-7ad35cd0026a.png)
Acho que o contraste de cores é legal - mas o espaço abaixo do título tá grande demais (o azul mais claro, o tamanho da vertical).

**Comment by greevin** [comment]
A intenção era fazer igual a parte do blog do site da CCNCC.

![ccncn eu- 1](https://user-images.githubusercontent.com/7833013/28750010-1cd35a8c-74b2-11e7-9476-9d6bda81981f.png)

Removi os estilos das páginas internas. Além disso, adicionei a opção de alterar a cor do cabeçalho e da letra nessas páginas.

![catedra dev-wp-admin-customize php-url http 3a 2f 2fcatedra dev 2fprojetos 2f](https://user-images.githubusercontent.com/7833013/28750019-e43f7574-74b2-11e7-9c4e-d31397088ef4.png)
