### ISSUE TITLE
Número de projetos/pessoas nas páginas internas

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#19]
Mudam - uma linha de 4 outra tem 2. Ou três e dois:
![screen shot 2017-07-29 at 15 19 24](https://user-images.githubusercontent.com/3904166/28747279-67905548-7471-11e7-88d5-e4f61da3ecce.png)

Vamos padronizar tudo em duas por linha tanto em projetos como pessoas?

**Comment by greevin** [comment]
Mudei o layout das páginas internas para mostrar 2 em cada linha.
