### ISSUE TITLE
Mudar estilo das "caixas" de notícias

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#2]
Podemos ser mais discreto aqui:
- Só ter título, data e resumo (sem comentários e autor)
- Deixar esse com dois por linha ao invés de três?
- Gostei do quadrado para diferenciar dos pesquisadores (circular)
- Remover os tags (e.g. projetos)

![screen shot 2017-07-24 at 11 17 00](https://user-images.githubusercontent.com/3904166/28527932-879eb48c-7062-11e7-8576-9e59181f5008.png)

**Comment by greevin** [comment]
Acertado a parte das 'Novidades' com as sugestões acima.
 ![novidades](https://user-images.githubusercontent.com/7833013/28544800-e95c314e-709a-11e7-8326-848c81697244.png)
