### ISSUE TITLE
Instalar plugin para contato

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#20]
Eu uso o Best Contact Form, mas pode ser qualquer um para mandar email. Vamos adicionar na página de contato.

**Comment by greevin** [comment]
Instalado o plugin 'Contact Form by BestWebSoft', creio que seja esse que está instalado no educacaoaberta.org.

**Comment by greevin** [comment]
Além da instalação, foi feito a estilização do formulário padrão para algo mais próximo do que está sendo usado no formulário dos 'Comentários'.
