### ISSUE TITLE
Página interna com dados precisa mudar de background color

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#22]
Fica estranha essa continuidade de cores entre o menu e os dados (tudo azul).  Quando customizarmos as cores, podemos usar o azul do rodapé (to usando essa paleta: http://paletton.com/#uid=13x0u0kqIf+fIq+lplkvIb0HX6o).

![screen shot 2017-07-29 at 15 54 30](https://user-images.githubusercontent.com/3904166/28747508-c314befe-7476-11e7-8286-722ccfb2a220.png)

**Comment by greevin** [comment]
Adicionei a opção de alterar as cores do fundo e da fonte do 'Mais Informações' através do 'Personalizar' do Wordpress.

![catedra dev-wp-admin-customize php-url http 3a 2f 2fcatedra dev 2f changeset_uuid 90c09675-c0bc-4cfb-aad3-54e005328ad6](https://user-images.githubusercontent.com/7833013/28749891-d6e6b456-74ac-11e7-8595-88ea550b1b9f.png)
