### ISSUE TITLE
Imagem inicial nem sempre ocupa toda a vertical

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#25]
Talvez não seja difícil resolver vendo o CSS do site que usamos como referência (https://ccncn.eu/). Veja como o ``Sobre`` aparece aqui sempre. Só num resize específico ele some. No site acima, ele nunca aparece. Pode ser que tenha a ver com proporção de imagem?

![screen shot 2017-07-29 at 21 10 12](https://user-images.githubusercontent.com/3904166/28749585-7bab92aa-74a2-11e7-89b8-e37de19aa85c.png)

**Comment by greevin** [comment]
Arrumado a questão da página principal ocupar toda a extensão da tela adicionando a medida 'vertical height' de 100vh. Para telas menores, foi necessário usar o calc para que não ficasse um espaço em branco na parte de cima da imagem.
