### ISSUE TITLE
Fonte do sub-título não é padrão

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#26]
Mudar: Fonte do Unicamp-Brasil  é ""Noto Sans", sans-serif"

![screen shot 2017-07-31 at 10 58 18](https://user-images.githubusercontent.com/3904166/28781075-41950ed2-75df-11e7-8fe4-bd8ca7a83173.png)

**Comment by greevin** [comment]
Alterado a fonte do sub-título para 'ArchivoNarrowRegular' (a mesma do título principal).
