### ISSUE TITLE
Alinhar mais informações para a esquerda

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#28]
Colocar a coluna da direita mais próxima.

Disso:
![screen shot 2017-07-31 at 11 06 55](https://user-images.githubusercontent.com/3904166/28781494-a1c25f66-75e0-11e7-9aed-0f21855f5f54.png)

Pra isso (ou ainda mais próximo se der):
![screen shot 2017-07-31 at 11 14 50](https://user-images.githubusercontent.com/3904166/28781749-7ea53a02-75e1-11e7-9fd4-908ff90e2394.png)

E pode tirar os ``:`` dois pontos, de cada um (e.g. ``Situação:`` para ``Situação``)
Mudar ``Equipes:`` para ``Equipe``

Sugiro remover a linha branca se alinhar bem. Acho que não precisa. 

Dá um mouse over e veja o movimento das flechas do ``Estratégias em um Novo Paradigma Globalizado`` - os itens vão para trás ao contrário dos outros.

**Comment by greevin** [comment]
- Removido os dois pontos dos campos;
- Removido a borda branca;
- Diminui o tamanho da coluna da esquerda para 30% e a da direita para 70%;

Com relação ao ultimo item, testei no Chrome, no Firefox e no Safari e não consegui identificar o que está acontecendo.
