### ISSUE TITLE
Float de página interna para imagem para direita

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#29]
Acho que a leitura fica melhor assim, já que todo o texto da página fica alinhado à esquerda:

![screen shot 2017-07-31 at 11 18 31](https://user-images.githubusercontent.com/3904166/28781909-08c738b6-75e2-11e7-876f-f6ba93757bc4.png)

Dei um ajuste: ``margin: X X X 15px` (aumentando o último) mas não sei se é pertinente, me pareceu melhor.

**Comment by greevin** [comment]
Alterado o float da página da esquerda pra direita.
