### ISSUE TITLE
Mudar "leias mais"

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#3]
Podemos usar algo mais discreto? Usando o contraste de funde ao invés de caixa? 
Poderíamos ter algo como "-> Leia mais" alinhado a esquerda. Sei que no site que te mandei eles usam caixas, mas não acho muito delicado aqui.

![screen shot 2017-07-24 at 11 24 52](https://user-images.githubusercontent.com/3904166/28527995-bdb19c74-7062-11e7-8f79-1567a77812b6.png)

**Comment by greevin** [comment]
Alterado o 'Leia Mais': foi retirado a caixa com o background escuro e foi adicionado uma seta do lado esquerdo e ao passar o mouse por cima, ele afasta da esquerda pra direita.
