### ISSUE TITLE
Rever destaque de projetos

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#31]
Não acho que tão legais... os outros (pessoas e destaques) ficaram bacanas, clean. O que você acha que podemos fazer?
![screen shot 2017-07-31 at 17 22 01](https://user-images.githubusercontent.com/3904166/28796653-c67af96a-7614-11e7-95ba-eb4e9c88c575.png)

Pensei em colocar o banner de texto mais pra baixo e ocupar o comprimento todo.

![screen shot 2017-07-31 at 17 21 19](https://user-images.githubusercontent.com/3904166/28796654-c72a220a-7614-11e7-9f8c-3d2bd3fd8a2a.png)

Ou algo mais assim, do https://www.minhacampinas.org.br, com um border.
![screen shot 2017-07-31 at 17 27 01](https://user-images.githubusercontent.com/3904166/28796850-81b4088e-7615-11e7-8e0f-b12f433e746a.png)

Ou ainda remover todo o frufru e ficar igual o do destaque, só que três por linha: com titulo, descritivo e afins. O que pensa?

**Comment by greevin** [comment]
Segui o mesmo padrão do 'Novidades', só que sem a parte do texto com apenas o título e o link para 'Leia Mais'.

![catedra dev- 4](https://user-images.githubusercontent.com/7833013/28803108-75b66f2a-7630-11e7-821e-fb792b9c1baf.png)
