### ISSUE TITLE
Mudar link color/hover para fundos escures

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#32]
Esses de destaque sempre vão ser escuros, só ajustar para a mesma cor do texto e depois no hover, não seja escuro (pode ser uma outra cor clara). Padronizar no tema como um todo.

![screen shot 2017-08-04 at 08 47 20](https://user-images.githubusercontent.com/3904166/28967461-9bb22fac-78f1-11e7-8bc2-3faeaa9be9f0.png)

**Comment by greevin** [comment]
Alterado a cor do link para branco e do hover para branco também mas com a opacidade de 0.7 (que deixa um pouco mais claro)
