### ISSUE TITLE
Mover título mais pra baixo

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#33]
Fica mais elegante. Senão fica tudo comprimido no topo.
Aqui, só mudei o padding e ficou ok, mas não sei se afeta mobile, etc:

![screen shot 2017-08-04 at 08 40 29](https://user-images.githubusercontent.com/3904166/28967479-ade6e2bc-78f1-11e7-994e-56a5a9671743.png)

**Comment by greevin** [comment]
Adicionado um padding-top de 30%. Com relação ao mobile ele não é afetado.
