### ISSUE TITLE
Colocar alguma coisa abaixo na seção do menu

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#34]
Seguindo o  modelo do http://inspirare.org.br/, acho que vale a pena colocar talvez ter um espaço abaixo no menu (onde eles tem onde "somos", etc) que esteja no tema. Não sei ainda o que é melhor colocar lá, mas a página fica em desequilíbrio visual sem algo para balancear. É fácil incorporar uma seção pequena lá para depois inserir algo? Ou melhor já definir?

**Comment by greevin** [comment]
Nesse caso, você pode usar a parte de 'Widgets' do próprio Wordpress para colocar coisas abaixo do menu. Isso já estava definido no próprio tema-pai.
