### ISSUE TITLE
Melhorar visibilidade do texto inicia

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#36]
Creio que fonte maior e cor mais clara para links a seguir/lidos. 
![screen shot 2017-08-08 at 14 32 40](https://user-images.githubusercontent.com/3904166/29085746-a03041e2-7c46-11e7-844c-ce2a8c064c92.png)

**Comment by greevin** [comment]
Aumentado a fonte para 1.75rem (17.5px) e alterado os links para branco com opacidade de 0.6.
