### ISSUE TITLE
Limitar número de posts em "novidades"

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#37]
Tentar pegar número de: ``Config->Configurações de leitura->As páginas do blog mostram no máximo``

Permitir depois um "ler" mais que vai para uma página interna com X posts por página e ``próximo``, ``anterior`` ou algo similar.

**Comment by greevin** [comment]
Agora o número de posts que aparece em 'Novidades' tanto na página inicial quanto na página interna é limitada pelo número que for determinado nas opções do Wordpress.

Na pagan interna, agora tem um paginador para as outras páginas, assim como acontece com a Pesquisa.
