### ISSUE TITLE
Data final de pesquisador pode ficar em branco

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#38]
Se ``ativo`` não tem data final.

**Comment by greevin** [comment]
Arrumado essa questão, caso o Pesquisador e/ou o Projeto não tem data de término mas está marcado como 'Ativo', ele será mostrado na tela inicial. Aproveitando isso, adicionei a palavra 'atual' quando não tiver uma data de término, agora fica: 08/08/2017 - atual.
