### ISSUE TITLE
Mudar gradiente default de background de imagem destaque

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#40]
Vamos usar branco -  o gradiente fica ruim com imagens transparente, ``png``.
![screen shot 2017-08-08 at 14 36 59](https://user-images.githubusercontent.com/3904166/29085899-1ec09a52-7c47-11e7-8572-42990f5b9ce4.png)

**Comment by greevin** [comment]
Quando não tiver imagem, o fundo fica com o mesmo gradiente, quando tiver imagem, o background fica branco.

![bkg2](https://user-images.githubusercontent.com/7833013/29092738-c4884ee2-7c5d-11e7-9346-44862a3ffdb4.png)

![bkg1](https://user-images.githubusercontent.com/7833013/29092759-cc594414-7c5d-11e7-90f5-6edc3a5c8701.png)
