### ISSUE TITLE
Ajustar CSS básico de texto

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#41]
Veja aqui, precisamos de uma harmonia de tamanho, alinhamento, e bold que fique legal.

http://educacaoaberta.org/novo/seminario-rea-2011/

![screen shot 2017-08-08 at 14 39 39](https://user-images.githubusercontent.com/3904166/29086010-78e9c030-7c47-11e7-828f-a4298aebce1a.png)

**Comment by greevin** [comment]
Arrumado o estilo das listas com números e bolinhas.

![lista](https://user-images.githubusercontent.com/7833013/29100952-707f6e20-7c85-11e7-9793-e0f9b806b6d5.png)
