### ISSUE TITLE
Estilizar caixa de busca e página de resultados

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#42]
Esqueci que não havia isso, importante.

- Coloquei lá, mas queria ver se alinhávamos ela pra baixo, mais próximo do footer. 
- Precisa estilizar a palavra "pesquisar" para mesma fonte (que fica dentro da caixa)
- Além disso, como não tinha isso antes, não dava pra ver. Veja que o resultado precisa mudar. Creio que seria bom ser como no padrão que estamos usando na página interna, com cabeçalho etc e com dois por linha, senão fica muito grande (um por tela). Acho que só falta implementar.

![screen shot 2017-08-08 at 17 29 01](https://user-images.githubusercontent.com/3904166/29093247-8b87203a-7c5f-11e7-835b-99abb3962cec.png)

**Comment by greevin** [comment]
Arrumado a caixa de pesquisa com a mesma fonte do texto e colocada um pouco perto do fim do menu;
Arrumado a página de pesquisa para o estilo das outras páginas, assim como a visualização do resultado da busca;

![catedra dev--s tel](https://user-images.githubusercontent.com/7833013/29100791-5e32b6f6-7c84-11e7-93ab-f110336500a4.png)
