### ISSUE TITLE
Aumentar texto do menu

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#43]
Acho que tá pequeno demais mesmo...a fonte parece não ficar boa muito pequena, fica fina.

![screen shot 2017-08-08 at 17 35 03](https://user-images.githubusercontent.com/3904166/29093349-ec049636-7c5f-11e7-80ae-4705abfce5ae.png)

**Comment by greevin** [comment]
Alterado o tamanho para 1.5rem (15px).
