### ISSUE TITLE
Jogar "ler todos" perto do título

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#44]
acho que fica mais intuitivo se estiver logo após o "Novidades" (próximo do texto) e não no canto direito.

Também deve ser "Ler todas" (novidades).

![screen shot 2017-08-09 at 09 33 09](https://user-images.githubusercontent.com/3904166/29121888-c8e93512-7ce6-11e7-8dac-726e9e85ae5d.png)

**Comment by greevin** [comment]
Resolvido na issue #37.
