### ISSUE TITLE
Permitir "resumo" nas postagens

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#45]
O WP tem a função "resumo" que é o que aparece logo após o título. Normalmente ele "trunca" o texto e coloca ``...``, como aqui:
![screen shot 2017-08-09 at 09 44 07](https://user-images.githubusercontent.com/3904166/29122052-4c835d44-7ce7-11e7-86dd-801ad6845eb3.png)

Mas há sempre opção de escrver outra coisa, como `` Coordenador da Cátedra``.
Para isso, precisamos do campo Resumo que aparece logo abaixo do WYSIWIG do post:
![screen shot 2017-08-09 at 09 43 22](https://user-images.githubusercontent.com/3904166/29122091-6c62408a-7ce7-11e7-92b1-ba4312efd62f.png)

Normalmente ativamos isso aqui nas opções do post, mas no tema não aparece.
![screen shot 2017-08-09 at 09 43 31](https://user-images.githubusercontent.com/3904166/29122106-79c38504-7ce7-11e7-8fdb-7a27bcf9e42b.png)

**Comment by greevin** [comment]
Adicionado a opção 'Resumo' nos tipos 'Projetos' e 'Pessoas'. Quando você coloca o resumo, ele aparece na página inicial e no post como se fosse um subtítulo.

**Comment by tamielbr** [comment]
No WP, por default, ele eliminar/substitui o texto truncado quando há um resumo.
- Precisa de um espaçamento maior entre o texto e o resumo (como era antes com o texto truncado).

![screen shot 2017-08-09 at 16 30 51](https://user-images.githubusercontent.com/3904166/29140215-2550c5ca-7d20-11e7-9620-72e8199f44ff.png)

**Comment by greevin** [comment]
Seria isso? Caso o post tenha resumo, ele só mostra o que aparece no resumo; caso não tenha, ele mostra o conteúdo.

![catedra dev- 2](https://user-images.githubusercontent.com/7833013/29152025-41c9e28c-7d5b-11e7-96aa-45f3aeeb6a3b.png)
