### ISSUE TITLE
Nova categoria no menu tem problemas

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#46]
Queria adicionar um novo elemento no menu, então adicionei a categoria ``Arquivo`` (coisas antigas). Duas coisas acontecem:

O descritivo aparece mesmo em outro browser depois de removido dentro do campo ``descrição`` da categoria no wp-admin). De modo geral poderíamos eliminar isso, a ``descrição`` nunca deve aparecer mesmo. Acho que isso acontece porque é ``cateogoria`` que não havíamos contemplado.

![screen shot 2017-08-09 at 10 14 31](https://user-images.githubusercontent.com/3904166/29123430-1f66fb9a-7cec-11e7-919c-8f2021a7c84a.png)

O resultado aparece com um template antigo (acho que seria o caso de aplicar a mesma solução do #37).

![screen shot 2017-08-09 at 10 15 15](https://user-images.githubusercontent.com/3904166/29123440-259163ac-7cec-11e7-9f58-18043be7894d.png)

Depois que vou pro resultado (depois de clicar ``Arquivo``) ele some do menu.

![screen shot 2017-08-09 at 10 15 20](https://user-images.githubusercontent.com/3904166/29123457-3320b77a-7cec-11e7-8fce-f7a3e0d4d657.png)

**Comment by greevin** [comment]
Adicionado o menu-item-description como display:none para que não apareça a descrição da categoria no menu. Arrumado a página de 'Arquivo' (archive.php) para que ela ficasse com a mesma cara das outras páginas.
