### ISSUE TITLE
Caixa de busca muda de lugar em ENG/ESP

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#47]
![screen shot 2017-08-09 at 10 33 33](https://user-images.githubusercontent.com/3904166/29124099-46d8a258-7cee-11e7-8045-af6ebdeda04a.png)

**Comment by greevin** [comment]
Testei no Firefox e no Chrome e, a primeira vez que eu acessei por causa do cache, ele mostrou a caixa de busca no lugar errado. Mas ao atualizar várias vezes, ele ficou no lugar correto.
