### ISSUE TITLE
<a> e <a hover> precisa de diferenciação nas páginas internas

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#48]
Na página interna não se identificam os links. Penso em cor azul, mais leve, talvez negrito, ou um underline bem leve azul (4B6F8A). Veja o que acha?

![screen shot 2017-08-09 at 16 25 41](https://user-images.githubusercontent.com/3904166/29140044-71538aa8-7d1f-11e7-948c-e0b74c023c92.png)

![screen shot 2017-08-09 at 16 22 59](https://user-images.githubusercontent.com/3904166/29140046-72062546-7d1f-11e7-8f9a-ce09ef99bfbd.png)

**Comment by tamielbr** [comment]
Solução do #52 para bom aqui.

**Comment by greevin** [comment]
Adicionei a cor preta nos links dos posts e coloquei a fonte em negrito para poder diferenciar que isso é um link.

![links](https://user-images.githubusercontent.com/7833013/29177575-6c1d32c2-7dc5-11e7-9083-053ca511baa2.png)

**Comment by greevin** [comment]
Como a fonte que estamos usando é fina, não consegui fazer ficar mais grossa. No caso acima, o que eu fiz anteriormente foi colocar um text-shadow, mas ele fica muito estranho. Com isso, resolvi deixar o border-bottom apenas para os links dentro de um post.

![links](https://user-images.githubusercontent.com/7833013/29241114-5ef5851a-7f49-11e7-8aef-89ec4654d125.png)

**Comment by tamielbr** [comment]
Aqui a fonte bold tmbm tá meio feia. Precisa arrumar o CSS? ou Vc acha que devemos rsolver isso usando outra fonte que tenha bold natural?

![screen shot 2017-08-14 at 21 28 03](https://user-images.githubusercontent.com/3904166/29297470-9ebd0fe8-8137-11e7-9eb9-ed4bbf688448.png)

![screen shot 2017-08-14 at 21 29 38](https://user-images.githubusercontent.com/3904166/29297485-b26be334-8137-11e7-808c-5a76b93fbd0a.png)

**Comment by greevin** [comment]
Pois é, acho que é melhor escolher uma outra fonte para que ela tenha o bold e regular natural já que a fonte escolhida só tem o formato 'light'.

Segue algumas sugestões:
https://fontlibrary.org/en/font/petra-sans
https://fontlibrary.org/en/font/clear-sans
https://fontlibrary.org/en/font/news-cycle
https://fontlibrary.org/en/font/franko-and-franco

**Comment by tamielbr** [comment]
acho que a news cycle fica bacana, vamos testar?

**Comment by greevin** [comment]
Alterada a fonte dos textos para News Cycle Regular e os elementos b e strong para News Cycle Bold, já estão disponíveis para visualização no site.

**Comment by tamielbr** [comment]
Acho que com a fonte nova não precisa mais do border bottom. Podemos fazer ela ``preto`` ou ``bold`` e texto esse cinza escuro e acho que já temos contraste, não é?

![screen shot 2017-08-15 at 11 28 26](https://user-images.githubusercontent.com/3904166/29320276-0884e192-81ad-11e7-847e-3542b79f91cc.png)

**Comment by tamielbr** [comment]
Acho que podemos tentar o mesmo no footer, veja que inclusive a imagem aparece com ``border-bottom``
![screen shot 2017-08-15 at 11 43 01](https://user-images.githubusercontent.com/3904166/29320872-0403da4a-81af-11e7-938d-e9bc8e0153fb.png)

**Comment by greevin** [comment]
Removido o border-bottom do link do rodapé e adicionado o bold para o link.
