### ISSUE TITLE
Problemas com links entre idiomas

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#49]
Tenho um exemplo concreto que preciso de ajuda. Tenho a página do IV WREA em três idiomas. A de ``pt`` é curta, só landing page e aponta para duas páginas completas em ``en`` e ``es`` (se quiser, veja no -> http://educacaoaberta.org, como exemplo funcionando com o antigo plugin (``bogo``). Quando eu tento fazer isso no site novo, mudei o nome do post para ``4th workshop REA``:

![screen shot 2017-08-09 at 16 39 14](https://user-images.githubusercontent.com/3904166/29140706-c612afb8-7d21-11e7-9660-a4bb7039d0ca.png)

...e abro o post em ``pt``. o Link de idiomas aparece na parte direita e tento selecionar, mas o post não existe:

![screen shot 2017-08-09 at 16 38 37](https://user-images.githubusercontent.com/3904166/29140689-b9aefa92-7d21-11e7-9219-37ecc345ef3a.png)

Quando entro no site ``/es``, vejo _todos_ os posts, só que claro, as bandeirinhas agora são ``en`` e ``pt``, tranquilo. Mas não sei se esses posts são _os mesmos_ do PT ou se são duplicadas que posso eliminar agora. Entende a confusão? ;)

**Comment by greevin** [comment]
Eu consegui achar o post na listagem (ele é o primeiro agora por causa do número).

![sem titulo](https://user-images.githubusercontent.com/7833013/29151250-52f2722c-7d56-11e7-80ad-6e95dd5b6f59.png)

**Comment by tamielbr** [comment]
Viche. Erro meu. Vou experimentar isso com mais calma.
