### ISSUE TITLE
Rodapé pode ocupar toda largura

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#5]
No direito, ele não vai até o fim. Fácil fazer? 

![screen shot 2017-07-26 at 15 14 04](https://user-images.githubusercontent.com/3904166/28636640-2d06742e-7215-11e7-83ab-dc786105a3a5.png)

Se puder ter fundo no azul (#123652) e reduzir o tamanho do texto, melhor.

**Comment by greevin** [comment]
A parte do tamanho do rodapé já foi resolvido em #16.

**Comment by greevin** [comment]
Acertado as cores do rodapé: azul #123652 com letras brancas e texto com tamanho de 1.25rem (ou 12.5px)

![catedra dev- 2](https://user-images.githubusercontent.com/7833013/28740436-04efd83c-73db-11e7-8b6e-c89e7aba16fe.png)
