### ISSUE TITLE
Projeto criado não aparece

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#50]
Criei um para o MIRA, mas nada aparece, tentei 2 browsers.

**Comment by greevin** [comment]
O projeto está com status 'Inativo' e o ano de término do mesmo é 2014, por isso ele não vai aparecer na tela inicial.
![educacaoaberta org-novo-wp-admin-post php-post 3646 action edit](https://user-images.githubusercontent.com/7833013/29150713-c78848a4-7d52-11e7-939a-efebe1436951.png)

Mas ele está aparecendo na página de 'Projetos' normalmente.
![educacaoaberta org-novo-projetos-](https://user-images.githubusercontent.com/7833013/29150730-d9779218-7d52-11e7-97e1-4e5a2e31fe85.png)
