### ISSUE TITLE
"Ver todos" para outros itens

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#52]
Como os títulos (Colaboradores, Projetos) não parecem links, me pergunto se não temos que:

1. ou padronizar os links para que fiquem óbvios (me parece melhor, menos texto na tela, mais intuitivo) - só não sei se underline sutil ou outro artifício é melhor (?)

2. colocar um "ler todos" como no novidades. 

Do jeito que tá fica difícil a pessoa saber que pode clicar e ver outras pessoas e projetos antigos. Ademais, como o menu só rola a tela e não vai pra página interna, não aponta para a existência de outras coisas antigas.

O que pensa?

**Comment by greevin** [comment]
Tomando como exemplo o site do CCNCN, eles usam a cor do texto mais clara e o link mais escuro.

![ccncn](https://user-images.githubusercontent.com/7833013/29151798-e9093036-7d59-11e7-8d37-19d99213d550.png)

Poderíamos fazer algo parecido. Um exemplo parecido está acontecendo com o 'Colaboradores' que o nome da pessoa está com a cor escura e o texto claro.

**Comment by tamielbr** [comment]
Me parece que ficaria bom sim no texto, como menciono no #48. Gostei da ideia. Precisamos ver se fonte se comporta bem. Mas não acho que isso resolveria o título...

**Comment by tamielbr** [comment]
Alguma ideia de como resolver a ideia dos títulos (e.g. saber que "Projetos" leva a todos os projetos? Pensei em uma flecha com ``-> Veja todos``. No nosso site referência, eles colocam no canto direito, pensei que fica bom ai, ou no final da seção. O que acha?

![screen shot 2017-08-22 at 16 28 44](https://user-images.githubusercontent.com/3904166/29583562-07b3317e-8757-11e7-9302-f2557aa88d1a.png)

**Comment by greevin** [comment]
Uma coisa que a gente poderia testar também é colocar a seta do lado do nome da seção, com isso elimina o texto adicional.

**Comment by tamielbr** [comment]
Pode ser. vamos testar?

**Comment by greevin** [comment]
Adicionado as setas nos nomes das páginas para indicar na tela inicial para indicar que existe mais coisa a ser explorada.

**Comment by tamielbr** [comment]
Acho que ficou meio feio antes e pequeno, destoa da leitura... podemos colocar:
- depois
- ajustando ao tamanho da letra (pode ser um pouco menor, mas centralizado na vertical)? 

tentei aqui mas não consegui no CSS.

**Comment by tamielbr** [comment]
No mobile ficou mais próximo, mas ainda desalinhado.
![screen shot 2017-08-22 at 20 34 30](https://user-images.githubusercontent.com/3904166/29592259-53c900c6-8779-11e7-88fb-29c3c607854a.png)

**Comment by greevin** [comment]
No mobile eu corrigi com a seta com tamanho menor. Você fala em colocar a seta depois do título ou como texto separado (igual ao site da CCNCN)?

**Comment by tamielbr** [comment]
Pensando aqui, acho que a seta não fica legal ai no texto do cabeçalho. Acho que poderíamos ver como fica com a seta ao final do texto (dentro da caixa/cor). Senão igual ao CCNCN. podemos experimentar e ver?

**Comment by greevin** [comment]
Deixei os dois juntos para que você pudesse ver como ia ficar. Troquei a posição da seta no título e adicionei o 'Leia Mais' do lado direito.

**Comment by tamielbr** [comment]
Que tal isso:

![screen shot 2017-08-23 at 13 58 05](https://user-images.githubusercontent.com/3904166/29628182-1aa0a7d0-880b-11e7-8481-3623b3a093df.png)

**Comment by greevin** [comment]
Verdade, é 'Ver todos' e não 'Leia mais'. Já alterei e removi a seta do lado do título.
