### ISSUE TITLE
Ajustes no CSS dos tipos de texto

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#53]
Acho que ainda falta padronizar e fazer uns ajustes, veja a página (http://educacaoaberta.org/novo/consultas-regionales-rea-participe/) como exemplo. Tem fontes diferentes, bold e não bold, tudo meio fora de padrão. Acho que os títulos ``h1, h2...`` precisam ser todos mesma fonte, talvez mudando tamanho e case, se for o caso.

![screen shot 2017-08-10 at 13 18 40](https://user-images.githubusercontent.com/3904166/29180746-1ef6b9be-7dcf-11e7-9382-72a400c369da.png)

O ``blockquote`` ta usando essa barra na vertical a esquerda, feio. Precisava ser algo com espaçamento à esqurerda, mostrando que é citação:

![screen shot 2017-08-10 at 13 19 23](https://user-images.githubusercontent.com/3904166/29180593-a0ed66b2-7dce-11e7-9cb7-8d8c2dc3ff5b.png)

**Comment by greevin** [comment]
Nesse caso, o que aconteceu é que eu coloquei o span com a mesma fonte dos headers (Archive Narrow), por isso o texto ficou com a fonte diferente. Adicionei o span na fonte dos textos (Gen Light).

**Comment by greevin** [comment]
Arrumado a questão da formatação dos elementos em um post. Corrigido o blockquote para que ele ficasse mais alinhado a esquerda e com itálico.

![blockquote](https://user-images.githubusercontent.com/7833013/29241226-f1ba27f0-7f4b-11e7-8341-e43dbf892ad8.png)

**Comment by tamielbr** [comment]
Acho que esse negrito tá punk ainda (``questões-chave``)

![screen shot 2017-08-15 at 11 28 02](https://user-images.githubusercontent.com/3904166/29320230-e9b96f26-81ac-11e7-8958-474faa01c372.png)

**Comment by greevin** [comment]
Adicionado o font-weight: normal; e font-style: normal; para os elementos H1 até H6 para que ele não ficasse com o bold tão grosso no Firefox.
