### ISSUE TITLE
Página rolando horizontalmente

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#54]
Pode ser que seja ``<table>`` que faz isso, se for, precisa de um ajuste no CSS, creio.
Veja: http://educacaoaberta.org/novo/projetos/mira-mapa-de-iniciativas-de-recursos-abertos/

![screen shot 2017-08-10 at 13 19 09](https://user-images.githubusercontent.com/3904166/29180845-71bc0974-7dcf-11e7-902b-857240cdde15.png)

**Comment by greevin** [comment]
Corrigido a estrutura da tabela que estavam com o mesmo tamanho da tabela do 'Mais Informações'.
