### ISSUE TITLE
Remover resumo da página interna

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#55]
Só fica no resumo mesmo ;) Aqui pode sair.

![screen shot 2017-08-10 at 13 27 49](https://user-images.githubusercontent.com/3904166/29180942-c2de9c9a-7dcf-11e7-872c-7762fab686da.png)

![screen shot 2017-08-10 at 13 46 13](https://user-images.githubusercontent.com/3904166/29181640-4accaa32-7dd2-11e7-92ad-eea09c659280.png)

**Comment by greevin** [comment]
Removido o resumo dos posts.
