### ISSUE TITLE
Notícias não precisa ser parte do formulário de projetos

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#57]
Vendo agora, acho que aos poucos isso ficará insustentável - muita coisa e difícil de saber só pelo título. 

Não quero complicar, mas pensei no seguinte: se cada projeto tivesse uma tag, e as notícias tivessem essa mesma tag, não daria para listar automaticamente ao invés de usar os checkboxes? Difícil?

**Comment by greevin** [comment]
Substituido a opção de marcar as noticias vindas através do 'Posts' por tags relacionadas. Com isso, ao adicionar uma tag dentro do projeto, é possível selecionar uma tag principal que vai mostrar todas as noticias que foram adicionadas a essa tag.

![catedra dev-wp-admin-post php-post 3657 action edit](https://user-images.githubusercontent.com/7833013/29565690-5a5f2b38-871d-11e7-9ed3-b2f2165a90fc.png)

Na página do 'Projeto', ele vai mostrar todas as noticias da tag que foi selecionada na tela do projeto.

![catedra dev-projetos-mira-mapa-de-iniciativas-de-recursos-abertos-](https://user-images.githubusercontent.com/7833013/29565718-6e47a9ae-871d-11e7-8537-e4b843fc60c2.png)

**Comment by tamielbr** [comment]
muito legal. perfeito.
