### ISSUE TITLE
Alinhar texto do destaque para vertical-align=top

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#60]
Equipe, Notícias, etc. ficam no meio. Devem ficar no topo.

![screen shot 2017-08-10 at 13 46 42](https://user-images.githubusercontent.com/3904166/29181673-6a17f8ba-7dd2-11e7-97bf-b937ccc8ac02.png)

**Comment by greevin** [comment]
Alterado o vertical-align=middle para vertical-align=top das tabelas.
