### ISSUE TITLE
Footer não fica no fim se página é pequena

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#61]
Lembro que já resolvi isso no passado com CSS, veja exemplo:
![screen shot 2017-08-10 at 14 54 51](https://user-images.githubusercontent.com/3904166/29184262-f900efe2-7ddb-11e7-84f8-066b662d9c71.png)

**Comment by greevin** [comment]
Corrigido a questão do footer não ficar na parte de baixo da página definindo a altura da página e do conteúdo.

Referência: https://codepen.io/cbracco/pen/zekgx
