### ISSUE TITLE
Ajuste fino das telas internas

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#62]
Um pouco compulsivo aqui, mas acho que precisa de uns ajustes. 

1. Menos espaço no header (azul, meio desproporcional grande embaixo) mas aumentando a distância branca entre o header e os posts.

2. Mais espaço entre os posts (retângulos) 

Não fiz ajuste de imagem, mas só pra ter uma ideia:

**Antes**
![screen shot 2017-08-10 at 15 10 16](https://user-images.githubusercontent.com/3904166/29184950-29581ed4-7dde-11e7-97e6-bc4eac9b58a4.png)

**Depois**
![screen shot 2017-08-10 at 15 10 07](https://user-images.githubusercontent.com/3904166/29184954-2e750238-7dde-11e7-8976-1e571033863d.png)

**Comment by greevin** [comment]
Agora existe um espaço maior entre os posts nas páginas. Alinhei os posts do lado esquerdo para que ele ficasse alinhado com o titulo.

![educacaoaberta org-novo-projetos- 1](https://user-images.githubusercontent.com/7833013/29241363-7328c09c-7f4e-11e7-8f05-c1aa963e100b.png)
