### ISSUE TITLE
Footer sobrepondo texto

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#63]
Ver: http://educacaoaberta.org/novo/projetos/formacao-educacao-aberta-e-recursos-educacionais-abertos/
![screen shot 2017-08-15 at 11 32 12](https://user-images.githubusercontent.com/3904166/29320400-6c77fc5c-81ad-11e7-98b2-af5fcbb89997.png)

**Comment by greevin** [comment]
Corrigido a altura do padding-bottom do body para telas maiores que 1240px.
