### ISSUE TITLE
Espaçamento vertical entre colaboradores, página principal

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#64]
Meio apertado entre o ``leia mais`` de cima e o nome de baixo. Pouca coisa mais fica melhor.

![screen shot 2017-08-15 at 11 27 10](https://user-images.githubusercontent.com/3904166/29320409-7ce8bff4-81ad-11e7-8069-566f9c924d36.png)

**Comment by greevin** [comment]
Adicionado um margin-bottom: 20px em cada elemento, além de ter colocado 3 colaboradores em cada linha agora para diminuir o espaço em branco nas páginas.
