### ISSUE TITLE
Feature imagem/melhorar display/crop

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#67]
Ele tá dando um crop e zoom na feature image (ou tentando que seja maior do que é). Conseguimos manter a imagem toda no tamanho máximo ou resolver de outra maneira, por exemplo, pra que o ``IV WREA`` apareça todo, e o do ``OER regional...`` apareça inteiro tmbm? Podemos preencher o background branco, mas desse jeito tá com baixa resolução e cortado.

**Comment by tamielbr** [comment]
![screen shot 2017-08-18 at 16 24 14](https://user-images.githubusercontent.com/3904166/29474390-e46f2808-8431-11e7-9011-abed00ad0025.png)

**Comment by greevin** [comment]
Corrigido o tamanho das imagens em 'Novidades' e 'Projetos' para que ela possa mostrar a imagem inteira. Tive que mudar o background-size de cover para 75%, com isso ele mostra toda a imagem.

![educacaoaberta org-novo- 1](https://user-images.githubusercontent.com/7833013/29477868-a6adae04-8440-11e7-8178-77a649e0bce6.png)
