### ISSUE TITLE
Reestilizar botão de comentário

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#7]
Podemos fazê-lo no mesmo molde da flexinha ``-> Publicar comentário`` , alinhado a esquerda?

![screen shot 2017-07-26 at 15 18 15](https://user-images.githubusercontent.com/3904166/28636820-c9288b26-7215-11e7-99d7-618c348d5c61.png)

**Comment by tamielbr** [comment]
Acho que poderia mudar também o resto aqui. Acho que "deixe um comentário" poderia sair fora. Que tal algo como:

``Comentando como [user]:``

![screen shot 2017-07-26 at 15 40 32](https://user-images.githubusercontent.com/3904166/28637698-d16f6680-7218-11e7-8d1a-61f35f7332ea.png)

**Comment by tamielbr** [comment]
Acho que aqui dá pra deixar só ``[X] comentários`` e tirar o nome do post, ficar menor o texto.
![screen shot 2017-07-26 at 20 57 11](https://user-images.githubusercontent.com/3904166/28648566-13d4ae64-7245-11e7-83eb-04e7e1173034.png)

**Comment by greevin** [comment]
Alterado a parte dos comentários, conforme especificado acima.

Com o usuário logado no sistema
![catedra dev-pessoas-mrs-hudson-](https://user-images.githubusercontent.com/7833013/28741358-d9949622-73ea-11e7-9333-3db13f8655bf.png)

Com um visitante do site
![catedra dev-pessoas-mrs-hudson- 1](https://user-images.githubusercontent.com/7833013/28741362-e46d8702-73ea-11e7-8d12-08e2adb6f695.png)

E o número de comentários sem o nome do post
![catedra dev-pessoas-mrs-hudson- 2](https://user-images.githubusercontent.com/7833013/28741365-f02c164e-73ea-11e7-970f-22b65fb158dc.png)
