### ISSUE TITLE
Remover espaço à esquerda do texto (border)

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#70]
Tentei, mas o elemento tem ``padding`` e não consigo fazer o ``border-bottom`` começar onde começa o texto; ele acaba começando antes, alinhado à pagina. Algum fix fácil para isso? 

![screen shot 2017-08-19 at 00 48 49](https://user-images.githubusercontent.com/3904166/29483227-45848ad4-8478-11e7-88a4-ee59c676890e.png)

**Comment by tamielbr** [comment]
Acho que é uma questão maior, que o alinhamento tá mais para a direita pra quase tudo. To ainda experimentando aqui mas acho que essa é a versão final (mais branco). Seria legal alinhar tudo (como usamos cores antes, ficava bem delimitado, agora com white space, fica estranho). Só mesmo pra saber por hora se tem um fix rápido pra isso e depois fecho isso.

![screen shot 2017-08-19 at 01 05 12](https://user-images.githubusercontent.com/3904166/29483341-94c0b288-847a-11e7-8257-8d765c42b5c0.png)

**Comment by greevin** [comment]
Adicionei o padding: 0 em cada um dos títulos onde foi definido o border-bottom para que eles ficassem alinhados mais a esquerda, com isso, tive que retirar o padding dos conteúdos dentro de cada seção. Uma sugestão seria usar o border-top em vez do border-bottom para criar essa linha, creio que fica bem melhor.

![bla](https://user-images.githubusercontent.com/7833013/29483676-00438a4c-8482-11e7-8056-54229e2b8567.png)
