### ISSUE TITLE
Customizar texto

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#71]
Ficou ótimo no meio da imagem, mas falta agora poder customizar via CSS, não vi nenhum selector pra ele. 

![screen shot 2017-08-21 at 09 57 41](https://user-images.githubusercontent.com/3904166/29520430-60617ec6-8657-11e7-8b07-1899d3822132.png)

**Comment by greevin** [comment]
Dá pra customizar pelo seletor '#pagina-inicial .entry-content p', coloquei a cor e o tamanho da fonte por lá.

#pagina-inicial .entry-content p {
	color: white;
	font-size: 20px;
}

**Comment by tamielbr** [comment]
Como tira o italico? não vi nada lá.

**Comment by greevin** [comment]
O italico você pode tirar na própria página: http://educacaoaberta.org/novo/wp-admin/post.php?post=530&action=edit
