### ISSUE TITLE
Imagens em linha única no mobile

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#72]
No mobile acho que a imagem não deve ter texto no contorno - ficando sozinhas e depois o texto, senão fica feio.

![2017-08-22 15 30 55](https://user-images.githubusercontent.com/3904166/29581178-edda5b22-874e-11e7-90f7-fec4ce797cc1.jpg)

**Comment by greevin** [comment]
Corrigido a posição da imagem destacada no mobile.
