### ISSUE TITLE
Espaço maior entre conteúdo e menu

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#73]
Tenho a sensação que o conteúdo ``azul`` tinha que estar com espaço maior do menu (``verde``), acho que tá meio espremido. Podemos mudar o ``padding-left`` dessa seção toda e dar maior espaço?

![screen shot 2017-08-22 at 15 30 31](https://user-images.githubusercontent.com/3904166/29581248-1813c630-874f-11e7-983a-db990fd89150.png)

**Comment by greevin** [comment]
Isso é uma perspectiva do tamanho da tela. Testando em um monitor maior, realmente o espaço entre o conteúdo e o menu é maior, mas testando em uma tela menor, como o do meu Mac 13", ele fica certo.

**Comment by greevin** [comment]
Para monitores maiores (> 1403px), alterei a sidebar para 15% e o conteúdo para 85%. Em outros monitores (< 1403px), o tamanho continua o mesmo (20% para a sidebar e 80% para o conteúdo).
