### ISSUE TITLE
Problemas com iframe

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#74]
No original, mapa (globo e mental) aparecem: http://educacaoaberta.org/o-estado-da-producao-academica-em-portugues-sobre-rea/

Novo da erro: http://educacaoaberta.org/novo/projetos/bibliografia-sobre-rea/?preview_id=3806&preview_nonce=43b9d3295f&_thumbnail_id=-1&preview=true

Algum block no tema?

**Comment by greevin** [comment]
Por algum motivo que eu desconheço, ele não copiou o iframe desses dois. Entrei no site original e copiei os iframes e funcionou.

http://educacaoaberta.org/novo/projetos/bibliografia-sobre-rea/
