### ISSUE TITLE
Ajustar mobile CSS da principal

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#75]
![2017-08-22 20 31 17](https://user-images.githubusercontent.com/3904166/29592154-dd7cbd7c-8778-11e7-8fd2-48ad82023bf1.jpg)

**Comment by greevin** [comment]
Corrigido, tive que tirar a configuração que estava no 'CSS Adicional' e tive que adicionar no style.css do tema para que pudesse mudar o tamanho da fonte em diferentes tamanhos.
