### ISSUE TITLE
Ajuste de tamanho de resumos/imagens em páginas maiores

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#77]
Não sei se é rápido e fácil, mas acho que na minha tela (15'') as imagens dos projetos/notícias ficam grandes demais. Reduzindo a horizontalidade da janela do browser, fica bem melhor. 

Numa tela grande, acho que fica precisando de mais white space. Se quiser podemos ver isso juntos alguma hora para um ajuste final. Coisa pouca, mas acho importante fazer esse pequeno ajuste.

Difícil mostrar isso em imagens aqui, mas veja a proporção do logo ``UNESCO`` e das imagens:

![screen shot 2017-08-29 at 20 06 56](https://user-images.githubusercontent.com/3904166/29848862-9a721ca8-8cf9-11e7-8400-747dcdb9ad79.png)

**Comment by greevin** [comment]
Creio que uma solução para monitores maiores que 15" seria colocar 3 por linha, com isso as imagens ficam menores.
![educacaoaberta org-novo-](https://user-images.githubusercontent.com/7833013/29849238-cfa8a3f4-8cfb-11e7-9fbf-e68313fd952d.png)

**Comment by greevin** [comment]
Alterei o CSS para que ele pudesse mostrar 3 por linha em monitores maiores para que você pudesse ver como ficou.

**Comment by tamielbr** [comment]
Ótimo.
