### ISSUE TITLE
Espaçamento entre título e imagem

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#78]
Parece que ele espera imagem quadrada, mas quase sempre será retangular. Fica uma espaço grande entre a imagem e o título, podemos reduzir?

![screen shot 2017-08-30 at 08 42 06](https://user-images.githubusercontent.com/3904166/29870713-4d45db16-8d5f-11e7-9c23-975b463b6df2.png)

**Comment by greevin** [comment]
Diminui o tamanho da altura das imagens que estavam em 350px para 200px e ficou perfeito para imagens retangulares. Já atualizei no Wordpress e está disponível para visualização (CMD+SHIFT+R para atualizar a página).
