### ISSUE TITLE
Reduzir imagem de destaque nos projetos

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#8]
Acho que está grande demais. Duas sugestões:
- Reduzir a imagem para um máximo vertical (e.g. 300px max)
- Alinhar a imagem a esquerda e deixar o texto de introdução fluir em volta dela.
- Remover a data do aqui, não é necessário.

![screen shot 2017-07-26 at 15 20 07](https://user-images.githubusercontent.com/3904166/28636860-f54b7d94-7215-11e7-9b5f-fcfc94dd08e4.png)

**Comment by greevin** [comment]
Acertado o tamanho da imagem e remoção da data no post. O texto agora fica do lado direito em volta da imagem.

![catedra dev-pessoas-mycroft-holmes-](https://user-images.githubusercontent.com/7833013/28690029-19f14dbc-72ee-11e7-869a-755d344415a2.png)
