### ISSUE TITLE
Trocar posicionamento da caixa de destaque

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#80]
Como são infos essenciais, acho que fica bem melhor logo acima.
![screen shot 2017-08-30 at 14 28 13](https://user-images.githubusercontent.com/3904166/29886154-870340ac-8d8f-11e7-9ace-a1ebb439f53c.png)

Trocar ``Agência(s) financiadora(s)`` por ``Financiamento``

**Comment by greevin** [comment]
Trocada a posição da Caixa de Destaque para depois do título e alterado 'Agência(s) financiadora(s)' para 'Financiamento'. Além disso, arrumei o espaçamento dentro da tabela para que ficasse com espaço tão grande.
