### ISSUE TITLE
Zotero na caixa de destaque

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#81]
Se eu quisesse colocar o ``shortcode`` que eu uso pro Zotero (bibliografia) dentro da caixa (último item) com cabeçalho ``Artigos``, seria fácil? Penso que poderia ter algo como uma caixa vazia que eu coloco o shortcode, como fazemos com "Financiadores" por exemplo. Fácil?

Algo assim, só que também dando um espaço um pouco maior entre cada referência:

![screen shot 2017-08-30 at 14 38 54](https://user-images.githubusercontent.com/3904166/29886601-fee78fb4-8d90-11e7-9331-3d864bb4ce62.png)

**Comment by greevin** [comment]
Adicionei um textarea chamado 'Publicações' no formulário do 'Projetos'. Usei o textarea para melhor visualização, já que o shortcode é grande. Adicionei também um margin-bottom para separar as referências. Fiz um de exemplo em http://educacaoaberta.org/novo/projetos/bibliografia-sobre-rea/, removi o 'Publicações' que estava no texto e coloquei dentro da caixa de destaque.

**Comment by tamielbr** [comment]
Legal! falta só mudar aqui o "agênicas". 
Ele força ``Nenhuma`` quando tá vazio, parece. Poderia ser como os outros, se não tem nada, não aparece?

![screen shot 2017-08-30 at 19 20 34](https://user-images.githubusercontent.com/3904166/29897652-61193d82-8db8-11e7-8f50-58172f32f2f8.png)

**Comment by greevin** [comment]
Ah sim, esqueci de trocar o nome do campo no formulário, Alterei o código para que ele pudesse aceitar valores vazios caso o mesmo já tenha sido adicionado anteriormente. Como exemplo, removi o 'Nenhuma' de 'Financiamento'.
