### ISSUE TITLE
Uso das flechas

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#82]
Vc acha que precisamos aqui? Agora me parece meio desnecessário
 já que o bold funciona bem. Que pensa?

![screen shot 2017-08-30 at 21 56 32](https://user-images.githubusercontent.com/3904166/29901401-2945f57e-8dce-11e7-8e1d-114b11c43323.png)

**Comment by greevin** [comment]
Sim, acho que agora podemos tirar as flechas nessa parte. Vou retirar as flechas do 'Projetos' e 'Colaboradores'.

**Comment by greevin** [comment]
As flechas foram removidas nas caixas de destaques.
