### ISSUE TITLE
Margem para conteúdo

### ISSUE THREAD

**Issue by tamielbr** [greevin/catedra-wptheme#83]
Ainda acho que precisamos de uma margem maior na esquerda e direita para o conteúdo. Nesse exemplo:
![screen shot 2017-10-28 at 13 15 50](https://user-images.githubusercontent.com/3904166/32135717-681b8196-bbe2-11e7-8e04-174b340ccd6b.png)

...dá pra ver como o "sobre" fica muito perto do logo. E na margem da direita, o conteúdo quase bate na borda. Acho que precisamos um respiro,pra ficar mais assim:
![screen shot 2017-10-28 at 13 19 45](https://user-images.githubusercontent.com/3904166/32135737-b1083ee4-bbe2-11e7-8b72-1351b50ad3cc.png)

Aqui, só mexi no padding:
![screen shot 2017-10-28 at 13 19 28](https://user-images.githubusercontent.com/3904166/32135741-b97f75ec-bbe2-11e7-8af4-e4aefccbccec.png)

Mas foi geral, afetou a imagem de introdução, que ficou menor tmbm. O que acha?

**Comment by greevin** [comment]
Adicionei um padding esquerdo de 2% no título das seções e um padding direito de 3% nos conteúdos dentro das seções.
